name: pt_v7
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.4=py39h9ce1e76_0
  - cuda=11.7.1=0
  - cuda-cccl=11.7.91=0
  - cuda-command-line-tools=11.7.1=0
  - cuda-compiler=11.7.1=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cuobjdump=11.7.91=0
  - cuda-cupti=11.7.101=0
  - cuda-cuxxfilt=11.7.91=0
  - cuda-demo-suite=12.0.76=0
  - cuda-documentation=12.0.76=0
  - cuda-driver-dev=11.7.99=0
  - cuda-gdb=12.0.90=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.0.78=0
  - cuda-nsight-compute=12.0.0=0
  - cuda-nvcc=11.7.99=0
  - cuda-nvdisasm=12.0.76=0
  - cuda-nvml-dev=11.7.91=0
  - cuda-nvprof=12.0.90=0
  - cuda-nvprune=11.7.91=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-nvvp=12.0.90=0
  - cuda-runtime=11.7.1=0
  - cuda-sanitizer-api=12.0.90=0
  - cuda-toolkit=11.7.1=0
  - cuda-tools=11.7.1=0
  - cuda-visual-tools=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - gds-tools=1.5.0.59=0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufft-dev=10.7.2.124=h98a8f43_0
  - libcufile=1.5.0.59=0
  - libcufile-dev=1.5.0.59=0
  - libcurand=10.3.1.50=0
  - libcurand-dev=10.3.1.50=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2022.4.0.15=0
  - numpy=1.22.3=py39he7a7128_0
  - numpy-base=1.22.3=py39hf524024_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - pillow=9.0.1=py39h22f2fdc_0
  - pip=22.3.1=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - pytorch=1.13.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h67b0de4_1
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py39h06a4308_0
  - setuptools=65.6.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.1=py39_cu117
  - torchvision=0.14.1=py39_cu117
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - babel==2.11.0
    - backcall==0.2.0
    - base58==2.1.1
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - click==8.1.3
    - comm==0.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - datasets==1.18.2
    - debugpy==1.6.5
    - decorator==5.1.1
    - defusedxml==0.7.1
    - diff-match-patch==20200713
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - filelock==3.9.0
    - fire==0.4.0
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - huggingface-hub==0.11.1
    - importlib-metadata==6.0.0
    - inquirerpy==0.3.4
    - ipdb==0.13.11
    - ipykernel==6.20.2
    - ipython==8.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.11
    - jsonlines==3.0.0
    - jsonnet==0.18.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==7.4.9
    - jupyter-core==5.1.3
    - jupyter-events==0.6.3
    - jupyter-server==2.1.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==3.5.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.19.0
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mizani==0.8.1
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nbclassic==0.4.8
    - nbclient==0.7.2
    - nbconvert==7.2.8
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - nltk==3.6.7
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - overrides==6.1.0
    - packaging==23.0
    - palettable==3.3.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathos==0.2.8
    - pathtools==0.1.2
    - patsy==0.5.3
    - pexpect==4.8.0
    - pfzy==0.3.4
    - pickleshare==0.7.5
    - platformdirs==2.6.2
    - plotnine==0.10.1
    - pox==0.3.2
    - ppft==1.7.6.6
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.36
    - protobuf==4.21.12
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==10.0.1
    - pydot==1.4.2
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.4
    - pytz==2022.7.1
    - pyyaml==6.0
    - pyzmq==25.0.0
    - regex==2022.10.31
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - sacremoses==0.0.53
    - scipy==1.8.0
    - send2trash==1.8.0
    - sentencepiece==0.1.96
    - sentry-sdk==1.13.0
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - sklearn==0.0.post1
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.2
    - statsmodels==0.13.5
    - termcolor==2.2.0
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tokenizers==0.11.4
    - tomli==2.0.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.8.1
    - transformers==4.16.2
    - typing-utils==0.1.0
    - uri-template==1.2.0
    - wandb==0.13.5
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - widgetsnbextension==4.0.5
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.11.0